### ISSUE TITLE
Test color calibration with two scanners per color (before trying 3d method) 

### ISSUE THREAD

**Issue by RELNO** [RELNO/CSharpScope_Toolbox#8]

**Comment by RELNO** [comment]
http://www.alanzucconi.com/2015/09/30/colour-sorting/

**Comment by foldalma** [comment]
Testing Hue (above) and Luminosity (below):

![screenshot 2017-06-29 17 47 50](https://user-images.githubusercontent.com/5706296/27712031-2295cbfc-5cf3-11e7-80a6-cdf9c1be866e.png)

**Comment by RELNO** [comment]
Bars look nice! (even if incorrect :) 👍 
Let's try the method we've seen today (then easy to implement one)

**Comment by foldalma** [comment]
I actually used that to create the top bar, with modified HSV. I was thinking we can use these two bars to set the sample point qualities? 

Envoyé de mon iPhone

**Comment by foldalma** [comment]
Improved the isolation & I think this could work: 
(also much better since only the grid area is being sampled--post-keystone)

![screenshot 2017-06-30 10 54 39](https://user-images.githubusercontent.com/5706296/27741383-f1e882c0-5d82-11e7-9c00-aa46b9c1f958.png)

**Comment by foldalma** [comment]
![screenshot 2017-06-30 12 08 46](https://user-images.githubusercontent.com/5706296/27744425-718e04dc-5d8d-11e7-9cd6-0bd78128d8e6.png)

**Comment by foldalma** [comment]
### Hue:
Almost there--works for very different whites:

![screenshot 2017-06-30 13 58 31](https://user-images.githubusercontent.com/5706296/27748179-6157a118-5d9c-11e7-8de1-c60bee1bb020.png)

![screenshot 2017-06-30 13 59 00](https://user-images.githubusercontent.com/5706296/27748193-761d4710-5d9c-11e7-8a4e-06a6d4b785e5.png)

**Comment by foldalma** [comment]
### Reverted to placing samplers:

This is with 9 sample points & still has errors, but you can calibrate it and see if you think it's functional?

![screenshot 2017-06-30 16 39 32](https://user-images.githubusercontent.com/5706296/27753204-c4b63420-5db2-11e7-9b0e-d285fbdeb13f.png)

**Comment by RELNO** [comment]
Let's meet this morning and talk about it. Do we have a threshold setting?
That is, so we allow a certain 'radius' around the values of a given sample
point?
Also, we should add a visual indicator to the color we've selected - like a
small frame around the quad to indicate its current color  assignment.

**Comment by foldalma** [comment]
![screenshot 2017-07-05 11 26 41](https://user-images.githubusercontent.com/5706296/27879436-a0de2aa4-618f-11e7-9c34-f608cf78969c.png)
